[package]
name = "moonrs"
version = "0.1.0"
authors = ["paulyc <paulyc@quetzalcoatl.us>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vsop87 = "2.0"
hifitime = "1.0"
moonrs-lib = { path  = "lib" }
