[package]
name = "tetrabiblos"
version = "0.1.0"
authors = ["paulyc <paulyc@quetzalcoatl.us>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hifitime = "1.0"
tetrabiblos-lib = { path  = "lib" }
